# Generated by Django 4.1.4 on 2022-12-24 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Product_Name", models.CharField(max_length=150)),
                ("Product_Code", models.CharField(max_length=50, unique=True)),
                ("Product_Description", models.CharField(max_length=500)),
                (
                    "Creation_Date",
                    models.DateTimeField(blank=True, default=datetime.datetime.today),
                ),
            ],
        ),
    ]
