# Generated by Django 4.1.4 on 2022-12-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="products",
            table="Products",
        ),
    ]
