# Generated by Django 4.1.4 on 2022-12-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_products_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
