# Generated by Django 4.1.4 on 2022-12-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_products_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="status",
            new_name="Status",
        ),
    ]
